### ISSUE TITLE
Check for Missing Data

### ISSUE THREAD

**Issue by MicheleTobias** [datalab-dev/covid_worksite_exposure#41]
Let's make sure we didn't lose any data in the time it took to fix the large file size issue. I have a copy of the CSV from last week from the campus reporting site. Hopefully that will fill any gaps.

**Comment by erklopez** [comment]
It looks to me like there is no data missing, but it should be useful to see that csv, where can I find it?

**Comment by MicheleTobias** [comment]
I just emailed it to you.

**Comment by erklopez** [comment]
Confirmed that there is no data missing. It seems that Git Actions is capable of outputting the exposures.csv with the scraped data +our data even if it was not capable of processing the mapinput.txt because of the size. It is running it just as if we were to do it on our computer, so the error from the size of the file does not affect any script it successfully ran before that. That is great in case of future errors, it seems that our data would not be lost.
